#!/bin/sh

# ===========================================================================
#
#                            PUBLIC DOMAIN NOTICE
#            National Center for Biotechnology Information (NCBI)
#
#  This software/database is a "United States Government Work" under the
#  terms of the United States Copyright Act.  It was written as part of
#  the author's official duties as a United States Government employee and
#  thus cannot be copyrighted.  This software/database is freely available
#  to the public for use. The National Library of Medicine and the U.S.
#  Government do not place any restriction on its use or reproduction.
#  We would, however, appreciate having the NCBI and the author cited in
#  any work or product based on this material.
#
#  Although all reasonable efforts have been taken to ensure the accuracy
#  and reliability of the software and data, the NLM and the U.S.
#  Government do not and cannot warrant the performance or results that
#  may be obtained by using this software or data. The NLM and the U.S.
#  Government disclaim all warranties, express or implied, including
#  warranties of performance, merchantability or fitness for any particular
#  purpose.
#
# ===========================================================================
#
# File Name:  bt-load
#
# Author:  Jonathan Kans
#
# Version Creation Date:   2/6/19
#
# ==========================================================================

#  Front-end for expanding Entrez Direct style of command-line navigation to
#  external resources maintained by BioThings.io.  See comments in xplore
#  script for credits and references.

debug=false

if [ "$#" -gt 1 ]
then
  if [ "$1" = "-debug" ]
  then
    debug=true
    shift
  fi
fi

if [ "$#" -lt 1 ]
then
  echo "Must supply target argument"
  exit 1
fi

dst="$1"
shift

if [ -t 0 ]
then
  # take identifier from command line
  if [ "$#" -eq 1 ]
  then
    uids="$1"
  else
    echo "$0 needs argument from stdin or command line"
    exit 1
  fi
else
  # read identifiers piped from stdin
  uids=$(cat /dev/stdin)
fi

ids=$(echo "$uids" | sed -e 's/\>/\&gt;/g' | tr ',' '\n' |
      while read uid; do echo "<Id>$uid</Id>"; done)
echo "<opt>\n$ids\n</opt>" |
xtract -wrp ENTREZ_EXTEND -pattern opt -wrp Type -lbl "$dst" \
  -wrp Count -num Id -wrp Id -encode Id |
xtract -format
