#!/bin/sh

cmd="$1"
shift

useasp=`has-asp`

filter() {
  while read fl
  do
    if [ -f "$fl" ]
    then
      continue
    fi
    echo "$fl"
  done
}

do_download() {
  dir="$1"
  msk="$2"
  if [ "$useasp" = "true" ]
  then
    asp-ls "$dir" |
    grep "$msk" |
    filter |
    asp-cp "$dir"
  else
    ftp-ls ftp.ncbi.nlm.nih.gov "$dir" |
    grep "$msk" |
    filter |
    ftp-cp ftp.ncbi.nlm.nih.gov "$dir"
  fi
}

prepare_book_list() {
  echo "<OpenAccessSubset>"
  while IFS=$'\t' read pth titl pblshr dt accn upd
  do
    if [ -n "$accn" ]
    then
      echo "  <Book>"
      echo "    <Accn>$accn</Accn>"
      echo "    <Path>$pth</Path>"
      echo "    <Title>$titl</Title>"
      echo "  </Book>"
    fi
  done
  echo "</OpenAccessSubset>"
}

case "$cmd" in
  -h | -help | --help | help )
  cat <<EOF
USAGE: $0
       pmc-oa | pmc-bioc | bioconcepts | generif | meshtree | oa-list | oa-book | carotene
EOF
    exit 0
    ;;
  pmc-oa | -pmc-oa )
    do_download "pub/pmc/oa_bulk" "xml.tar.gz"
    exit 0
    ;;
  pmc-bioc | -pmc-bioc )
    do_download "pub/wilbur/BioC-PMC" "xml_unicode.tar.gz"
    exit 0
    ;;
  bioconcepts | -bioconcepts )
    do_download "pub/lu/PubTatorCentral" "chemical2pubtatorcentral.gz"
    do_download "pub/lu/PubTatorCentral" "disease2pubtatorcentral.gz"
    do_download "pub/lu/PubTatorCentral" "gene2pubtatorcentral.gz"
    exit 0
    ;;
  generif | -generif | generifs | -generifs )
    do_download "gene/GeneRIF" "generifs_basic.gz"
    do_download "gene/DATA" "gene_info.gz"
    if [ ! -f "genename.txt" ]
    then
      gunzip -c gene_info.gz |
      grep -v NEWENTRY |
      grep -v GeneID |
      cut -f 2,3 > genename.txt
    fi
    if [ ! -f "geneconv.xml" ]
    then
      cat genename.txt |
      xtract -t2x -set Set -rec Rec Code Name |
      xtract -format > geneconv.xml
    fi
    exit 0
    ;;
  meshtree | -meshtree )
    if [ ! -f "desc2020.xml" ]
    then
      echo "desc2020.xml"
      ftp-cp "nlmpubs.nlm.nih.gov" "online/mesh/MESH_FILES/xmlmesh" "desc2020.zip"
      unzip -qq desc2020.zip
      rm desc2020.zip
      chmod og-wx desc2020.xml
      chmod u-x desc2020.xml
    fi
    if [ ! -f "pa2020.xml" ]
    then
      echo "pa2020.xml"
      ftp-cp "nlmpubs.nlm.nih.gov" "online/mesh/MESH_FILES/xmlmesh" "pa2020.xml"
    fi
    if [ ! -f "qual2020.xml" ]
    then
      echo "qual2020.xml"
      ftp-cp "nlmpubs.nlm.nih.gov" "online/mesh/MESH_FILES/xmlmesh" "qual2020.xml"
    fi
    if [ ! -f "supp2020.xml" ]
    then
      echo "supp2020.xml"
      ftp-cp "nlmpubs.nlm.nih.gov" "online/mesh/MESH_FILES/xmlmesh" "supp2020.zip"
      unzip -qq supp2020.zip
      rm supp2020.zip
      chmod og-wx supp2020.xml
      chmod u-x supp2020.xml
    fi

    if [ ! -f "meshconv.xml" ]
    then
      cat supp2020.xml |
      xtract -wrp "Set,Rec" -pattern SupplementalRecord \
        -if "SupplementalRecord@SCRClass" -eq 1 \
        -or "SupplementalRecord@SCRClass" -eq 3 \
          -wrp "Code" -element "SupplementalRecord/SupplementalRecordUI" \
          -wrp "Name" -encode "SupplementalRecordName/String" |
      xtract -format > meshtemp.xml
      cat desc2020.xml |
      xtract -wrp "Set,Rec" -pattern DescriptorRecord \
        -wrp "Code" -element "DescriptorRecord/DescriptorUI" \
        -wrp "Name" -first "DescriptorName/String" \
        -wrp "Tree" -element "TreeNumberList/TreeNumber" |
      xtract -format >> meshtemp.xml
      cat meshtemp.xml | xtract -wrp Set -pattern Rec -sort Code > meshconv.xml
      rm meshtemp.xml
    fi

    if [ ! -f "meshtree.txt" ]
    then
      cat meshconv.xml |
      xtract -pattern Rec -if Tree -element Code -sep "," -element Tree > meshtree.txt
    fi

    if [ ! -f "meshname.txt" ]
    then
      cat meshconv.xml |
      xtract -pattern Rec -if Name -element Code -sep "," -element Name > meshname.txt
    fi

    exit 0
    ;;
  oa-list | -oa-list )
    if [ ! -f "books.xml" ]
    then
      nquire -ftp ftp.ncbi.nlm.nih.gov pub/litarch file_list.txt |
      prepare_book_list > books.xml
    fi
    exit 0
    ;;
  oa-book | -oa-book )
    accn="$1"
    shift
    if [ ! -f "books.xml" ]
    then
      nquire -ftp ftp.ncbi.nlm.nih.gov pub/litarch file_list.txt |
      prepare_book_list > books.xml
    fi
    cat books.xml |
    xtract -pattern Book -if Accn -equals "$accn" -element Path |
    while read pth
    do
      if [ ! -f "$pth" ]
      then
        ftp-cp ftp.ncbi.nlm.nih.gov "pub/litarch" "$pth"
      fi
    done
    exit 0
    ;;
  carotene | -carotene )
    if [ ! -f "carotene.xml" ]
    then
      do_download "entrez/entrezdirect/samples" "carotene.xml.zip"
      unzip -qq carotene.xml.zip
      rm carotene.xml.zip
    fi
    exit 0
    ;;
  * )
    break
    ;;
esac
