#!/bin/sh

xtract -pattern INSDSeq -pfx ">Feature " -first INSDSeqid \
  -group INSDFeature -FKEY INSDFeature_key \
    -block INSDInterval -pfc "\n" \
      -element INSDInterval_from,INSDInterval_to,INSDInterval_point,INSDInterval_point,"&FKEY" -FKEY "" \
    -block INSDQualifier -pfc "\n\t\t\t" \
      -element INSDQualifier_name,INSDQualifier_value
